version: "3"
services:
  api:
    image: node:8
    command: npm run install-start
    volumes:
      - ./api:/api/
    working_dir: /api/
    links:
      - db-postgres
    ports:
      - "3030:3030"
    environment:
      POSTGRES_HOST: db-postgres
      API_PORT: 3030
      NODE_ENV: development
  db-postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - /lib/postgresql
    environment:
      POSTGRES_PASSWORD: shejingbing
      POSTGRES_USER: nvwangdaren
      POSTGRES_DB: ocwahaha
  adminer:
        image: adminer
        ports:
            - 8081:8080
